const data = [
  {id: 1, url:require('./../../assets/images/cat.jpg'), likes: 1, comments: 2},
  {id: 2, url:require('./../../assets/images/daisy_flower.jpg'), likes: 100, comments: 200},
  {id: 3, url:require('./../../assets/images/dahlia.webp'), likes: 1, comments: 2},
  {id: 4, url:require('./../../assets/images/frog.jpg'), likes: 111, comments: 222},
  {id: 5, url:require('./../../assets/images/girl.jpg'), likes: 11, comments: 22},
  {id: 6, url:require('./../../assets/images/hedgehog.jpg'), likes: 10, comments: 20},
  {id: 7, url:require('./../../assets/images/landscape.webp'), likes: 1, comments: 2},
  {id: 8, url:require('./../../assets/images/poppy.webp'), likes: 1, comments: 2},
  {id: 9, url:require('./../../assets/images/rainbow.webp'), likes: 4, comments: 6},
  {id: 10, url:require('./../../assets/images/rose_garden.jpg'), likes: 1, comments: 2},
  {id: 11, url:require('./../../assets/images/swan.jpg'), likes: 1, comments: 3},
  {id: 12, url:require('./../../assets/images/squirrel.webp'), likes: 5, comments: 2},
  {id: 13, url:require('./../../assets/images/cat.jpg'), likes: 1, comments: 2},
  {id: 14, url:require('./../../assets/images/daisy_flower.jpg'), likes: 100, comments: 200},
  {id: 15, url:require('./../../assets/images/dahlia.webp'), likes: 1, comments: 2},
  {id: 16, url:require('./../../assets/images/frog.jpg'), likes: 111, comments: 222},
  {id: 17, url:require('./../../assets/images/girl.jpg'), likes: 11, comments: 22},
  {id: 18, url:require('./../../assets/images/hedgehog.jpg'), likes: 10, comments: 20},
  {id: 19, url:require('./../../assets/images/landscape.webp'), likes: 1, comments: 2},
  {id: 20, url:require('./../../assets/images/poppy.webp'), likes: 1, comments: 2},
  {id: 21, url:require('./../../assets/images/rainbow.webp'), likes: 4, comments: 6},
  {id: 22, url:require('./../../assets/images/rose_garden.jpg'), likes: 1, comments: 2},
  {id: 23, url:require('./../../assets/images/swan.jpg'), likes: 1, comments: 3},
  {id: 24, url:require('./../../assets/images/squirrel.webp'), likes: 5, comments: 2},
  {id: 25, url:require('./../../assets/images/cat.jpg'), likes: 1, comments: 2},
  {id: 26, url:require('./../../assets/images/daisy_flower.jpg'), likes: 100, comments: 200},
  {id: 27, url:require('./../../assets/images/dahlia.webp'), likes: 1, comments: 2},
  {id: 28, url:require('./../../assets/images/frog.jpg'), likes: 111, comments: 222},
  {id: 29, url:require('./../../assets/images/girl.jpg'), likes: 11, comments: 22},
  {id: 30, url:require('./../../assets/images/hedgehog.jpg'), likes: 10, comments: 20},
  {id: 31, url:require('./../../assets/images/landscape.webp'), likes: 1, comments: 2},
  {id: 32, url:require('./../../assets/images/poppy.webp'), likes: 1, comments: 2},
  {id: 33, url:require('./../../assets/images/rainbow.webp'), likes: 4, comments: 6},
  {id: 34, url:require('./../../assets/images/rose_garden.jpg'), likes: 1, comments: 2},
  {id: 35, url:require('./../../assets/images/swan.jpg'), likes: 1, comments: 3},
  {id: 36, url:require('./../../assets/images/squirrel.webp'), likes: 5, comments: 2},
  {id: 37, url:require('./../../assets/images/cat.jpg'), likes: 1, comments: 2},
  {id: 38, url:require('./../../assets/images/daisy_flower.jpg'), likes: 100, comments: 200},
  {id: 39, url:require('./../../assets/images/dahlia.webp'), likes: 1, comments: 2},
  {id: 40, url:require('./../../assets/images/frog.jpg'), likes: 111, comments: 222},
  {id: 41, url:require('./../../assets/images/girl.jpg'), likes: 11, comments: 22},
  {id: 42, url:require('./../../assets/images/hedgehog.jpg'), likes: 10, comments: 20},
  {id: 43, url:require('./../../assets/images/landscape.webp'), likes: 1, comments: 2},
  {id: 44, url:require('./../../assets/images/poppy.webp'), likes: 1, comments: 2},
  {id: 45, url:require('./../../assets/images/rainbow.webp'), likes: 4, comments: 6},
  {id: 46, url:require('./../../assets/images/rose_garden.jpg'), likes: 1, comments: 2},
  {id: 47, url:require('./../../assets/images/swan.jpg'), likes: 1, comments: 3},
  {id: 48, url:require('./../../assets/images/squirrel.webp'), likes: 5, comments: 2}

];

export default data;